development:
  adapter: postgresql
  encoding: unicode
  database: ninjasales_development
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: ninjasales_test
  pool: 5
  username: myapp
  password: password1
